### ISSUE TITLE
401 Authorization error

### ISSUE THREAD

**Issue by jo9182** [3kh0/discord-proxy#3]
Anytime I try to launch it from the github.io page it gives me a 401 Authorization error

**Comment by jo9182** [comment]
@3kh0 
Alright, good to know :)
Are you using Holy Unblocker as a kind of base for this?

**Comment by 3kh0** [comment]
> @3kh0 Alright, good to know :) Are you using Holy Unblocker as a kind of base for this?

yes, emerald and I am working on a direct proxy.

**Comment by jo9182** [comment]
> > @3kh0 Alright, good to know :) Are you using Holy Unblocker as a kind of base for this?
> 
> yes, emerald and I am working on a direct proxy.

Oh, that sounds cool, is it kind of like the discord tab on Holy Unblocker?

**Comment by 3kh0** [comment]
> > > @3kh0 Alright, good to know :) Are you using Holy Unblocker as a kind of base for this?
> > 
> > 
> > yes, emerald and I am working on a direct proxy.
> 
> Oh, that sounds cool, is it kind of like the discord tab on Holy Unblocker?

yes, a bit. My school blocked nginx which was the server the proxy ran on so we are finding a way to make a dynamic DNS server.
